default: clean training testing misc

training:
	python hw3.py stoplist.txt traindata.txt trainlabels.txt traindata.txt trainlabels.txt

testing:
	python hw3.py stoplist.txt traindata.txt trainlabels.txt testdata.txt testlabels.txt

misc:
	python hw3.py

clean:
	rm -f results.txt preprocessed.txt
