default: training testing

training:
	python hw3.py stoplist.txt traindata.txt trainlabels.txt traindata.txt trainlabels.txt

testing:
	python hw3.py stoplist.txt traindata.txt trainlabels.txt testdata.txt testlabels.txt

clean:
	rm results.txt
